extract:
    iris:
        type: CsvExtractor
        location: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv

load:
    processed_data:
        type: CsvLoader
        location: ./.output/iris_melt.csv


